### ISSUE TITLE
Followup from Reddit Discussion

### ISSUE THREAD

**Issue by davidbarsky** [skade/crates-io-changes-stream#4]
Hi Florian! I'm thramp, following up from [Reddit](https://www.reddit.com/r/rust/comments/79aplm/alternative_registries/dp37864/?context=3). I'm interested in helping out! Is there any place that'd be ripe for contribution?

(Also, please take your time to respond! This is not urgent, particularly if you have other obligations.)

**Comment by skade** [comment]
Hi thanks for getting in touch :).

I'll see that I can get the project at least to a state where you can run it on any crates.io checkout and then get back to you.

I have no particular direction for this project beyond wanting and helping it to exist, so I'm happy about any help :).

**Comment by davidbarsky** [comment]
I don't think I'm gonna get around to this—will close this issue.
